name: Publish Flows

on:
  push:
    branches: [main, develop]

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      location_dev: mypurecloud.com
      location_prod: mypurecloud.com

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Archy
        run: |
          cd ~
          mkdir archy
          wget https://sdk-cdn.mypurecloud.com/archy/latest/archy-linux.zip
          unzip archy-linux.zip -d archy
          cd archy
          ./archy version

      - name: Publish flows (dev)
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: "for filename in flows/*; do ~/archy/archy publish --location ${{ env.location_dev }} --clientId ${{ secrets.DEV_CLIENT_ID }} --clientSecret ${{ secrets.DEV_CLIENT_SECRET }} --file ${filename}; done"

      - name: Publish flows (prod)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: "for filename in flows/*; do ~/archy/archy publish --location ${{ env.location_prod }} --clientId ${{ secrets.PROD_CLIENT_ID }} --clientSecret ${{ secrets.PROD_CLIENT_SECRET }} --file ${filename}; done"
